runtime: python311

instance_class: F2

entrypoint: gunicorn -b :$PORT -w 2 --threads 4 --timeout 300 app:app

env_variables:
  FLASK_SECRET_KEY: "e84764c8447077ce1b3742f56006f71aee1eeebe494d24c2fa82b637a9dad2ad"
  TRADING_DB: "database/upstox_v3_live_trading.db"
  USER_DB: "database/users.db"
  PORT: "8080"
  HOST: "0.0.0.0"
  DEBUG: "False"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
